Repository hmcts/ccd-message-publisher, pull requests merged in 2021-12, with the labels that each got.

#138 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-138

#139 update log4j
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-139

#140 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-140

#141 CCD-2231: Updated CVE suppression dates
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-141

#142 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-142
