Repository hmcts/ccd-message-publisher, pull requests merged in 2021-01, with the labels that each got.

#22 Update testcontainers for Docker related bug
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-22

#25 Add util for reading from topics
  topic-reader-util/.gitignore
  topic-reader-util/README.md
  topic-reader-util/build.gradle
  topic-reader-util/gradle/wrapper/gradle-wrapper.jar
  topic-reader-util/gradle/wrapper/gradle-wrapper.properties
  topic-reader-util/gradlew
  topic-reader-util/gradlew.bat
  topic-reader-util/src/main/java/topic/TopicReader.java
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-25

#24 RDM-10811 Set case id as the SessionId when publishing messages
  src/integrationTest/java/uk/gov/hmcts/ccd/service/MessagePublisherRunnableIT.java
  src/integrationTest/resources/sql/insert-message-property-candidates.sql
  src/main/java/uk/gov/hmcts/ccd/service/MessageProperties.java
  topic-reader-util/.gitignore
  topic-reader-util/README.md
  topic-reader-util/build.gradle
  topic-reader-util/gradle/wrapper/gradle-wrapper.jar
  topic-reader-util/gradle/wrapper/gradle-wrapper.properties
  topic-reader-util/gradlew
  topic-reader-util/gradlew.bat
  topic-reader-util/src/main/java/topic/TopicReader.java
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-24
