Repository hmcts/ccd-message-publisher, pull requests merged in 2021-07, with the labels that each got.

#114 suppress cve
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-114

#116 updated json-smart library version
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-116

#117 fix for CVE-2021-29425
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-117

#120 fix for CVE-2021-33037
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-120

#119 CCD-1596 Integrate Fortify Scan into Nightly Pipelines - Message Publ…
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-119

#123 CCD-1330: Updated CVE suppression dates to 25/08/2021
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-123
