Repository hmcts/ccd-message-publisher, pull requests merged in 2021-03, with the labels that each got.

#40 RDM-11234 Upgrade Hikari CP Dependency in All CCD Apps
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-40

#44 RDM-11382 RDM-11387 RDM-11288 RDM-11430 RDM-11431 CVE's
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-44

#47 RDM-11529 CVE-2021-25122 (Message Publisher)
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-47

#52 RDM-11380 CVE-2017-1000190
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-52

#62 RDM-11765 Update CVE Suppress Until Date In All Services
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-62

#64 RDM-11729: Upgrade befta to 6.13.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-64

#65 RDM-11809 CVE-2021-21295 (CCD Message Publisher)
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-65

#57 RDM-11531 CVE-2020-13697
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-57
