Repository hmcts/ccd-message-publisher, pull requests merged in 2022-04, with the labels that each got.

#159 --Adding the Suppression for Spring Beans jar. Temporary Fix.
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-159

#158 spring framework version update to 5.3.18 from 5.3.15
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-158

#161 jackson.version update for CVE-2020-36518
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-161

#164 CVE Multiple issues suppressions
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-164
