Repository hmcts/ccd-message-publisher, pull requests merged in 2022-09, with the labels that each got.

#212 Suppress CVE-2022-25857 in suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-212

#211 CCD-3577 Cleanup CVE Suppressions
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-211

#215 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-215

#210 CCD-3648: Fix preview deploy issues
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-210

#206 CCD-3539: Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-206
