Repository hmcts/ccd-message-publisher, pull requests merged in 2022-12, with the labels that each got.

#228 CCD-4056 CVE-2016-4432 CVE-2016-3094 Suppression
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-228

#225 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-225

#227 CCD-4047-Fix-CVE-2022-41946
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-227

#230 CCD-4056: Move CVE-2016-3094 to false positives
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-230
