Repository hmcts/ccd-message-publisher, pull requests merged in 2022-11, with the labels that each got.

#222 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-222

#221 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-221

#223 CCD-3918 CVE-2022-42252
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-223

#224 CCD-3917 Spring Security Upgrade
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-224

#216 CCD-3533 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-216
