Repository hmcts/ccd-message-publisher, pull requests merged in 2022-06, with the labels that each got.

#176 CCD-3207 - Added switch to non-root user in Dockerfile
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-176

#184 CCD-3334 Regular Pipeline Maintenance - suppression CVE-2022-22978
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-184

#186 CCD-3387 Remove CVE Suppress Until Date from All Services
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-186

#188 CCD-3400: Suppression for CVE-2022-22950
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-188

#187 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-187

#192 CCD-3405: Move to False positives section
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-192

#195 Add comment to suppressions.xml
  charts/ccd-message-publisher/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-195
