Repository hmcts/ccd-message-publisher, pull requests merged in 2022-05, with the labels that each got.

#169 package update for CVE-2022-21724
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-169

#170 CCD-3106 - Updated build.gradle (spring-framework-version from 5.3.18 to 5.3.1.19)
  build.gradle
  charts/ccd-message-publisher/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-170

#173 CVE-2022-24823 : ccd-message-publisher fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-173

#174 suppression of CVE-2016-1000027 and until date extension for current …
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-174

#175 suppression of CVE-2022-29885
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-175

#178 CVE-2016-1000027 is noted as false positive
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-178

#181 CVE-2022-29885: ccd-message-publisher fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-181
