Repository hmcts/ccd-message-publisher, pull requests merged in 2022-01, with the labels that each got.

#144 Amend suppression dates by 1 month
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-144

#143 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-143

#145 Update to build.gradle
  Jenkinsfile_CNP
  build.gradle
  src/aat/java/uk.gov.hmcts.ccd.messagepublisher/befta/MessagePublisherTestAutomationAdapter.java
  src/aat/java/uk.gov.hmcts.ccd.messagepublisher/befta/TestDataLoaderMain.java
  topic-reader-util/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-145
