Repository hmcts/ccd-message-publisher, pull requests merged in 2023-05, with the labels that each got.

#247 CCD-4479, CCD-4509- Fix for CVE-2023-20861,CVE-2023-20860
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-247

#251 CCD-4056 : Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-251

#254 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-254

#253 CCD-4687 Update renovate.json
  .github/renovate.json
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-253
