Repository hmcts/ccd-message-publisher, pull requests merged in 2023-01, with the labels that each got.

#233 CCD-4157: Suppress CVE
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-233

#232 CCD-4163 Bump rse-gradle-java-plugin
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-232

#237 Update Chart.yaml
  charts/ccd-message-publisher/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-237
