Repository hmcts/ccd-message-publisher, pull requests merged in 2024-10, with the labels that each got.

#303 CCD-5158 Upgrade Tomcat to fix CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-303

#314 tidy up suppressions
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-314

#315 CME-54 update to Java 21
  .github/workflows/dependency-check.yml
  Dockerfile
  README.md
  acb.tpl.yaml
  build.gradle
  topic-reader-util/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-315
