Repository hmcts/ccd-message-publisher, pull requests merged in 2024-03, with the labels that each got.

#273 CVE fixes 010224
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-273

#248 Ccd 4412 deprecated service urls
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-248

#276 Fix CVE-2023-41080 : Update org.apache.tomcat.embed to 9.0.82
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-276

#281 Revert pr276
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-281

#283 Update build.gradle
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-283
