Repository hmcts/ccd-message-publisher, pull requests merged in 2024-07, with the labels that each got.

#295 Befta-fw 9.0.2, ccd-test-definitions 7.22.2, gradle 8.7
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/aat/java/uk.gov.hmcts.ccd.messagepublisher/befta/MessagePublisherBeftaRunner.java
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-295

#280 5025 Changed version number to resolve CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-280

#291 CCD-5475: bumped tomcat version to 9.0.82
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-291
