Repository hmcts/ccd-message-publisher, pull requests merged in 2024-08, with the labels that each got.

#301 Chart upgrades (servicebus and java)
  charts/ccd-message-publisher/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-301

#300 enable fortify failure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-300

#304 CCD-5022 False Positive suppress CVE-2023-36414/5
  charts/ccd-message-publisher/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-304

#305 fix nightly
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-305

#306 CCD-5159:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-306

#296 CCD-5518 : Fix-CVE-2024-1597
  build.gradle
  charts/ccd-message-publisher/Chart.yaml
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-296

#307 Revert "CCD-5159:"
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-307
