Repository hmcts/ccd-message-publisher, pull requests merged in 2024-11, with the labels that each got.

#312 CCD-5833:
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-312

#316 CCD-5952: Fix-CVE-2024-43591
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-316

#309 CCD-4974:
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-309
