Repository hmcts/ccd-message-publisher, pull requests merged in 2025-01, with the labels that each got.

#319 CCD-4975:
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-319

#321 CCD-6049 : Bump ccd-test-definitions and befta-fw to latest
  build.gradle
Labels: ns:ccd, prd:ccd

#322 CCD-5632:
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd

#299 CCD-4373
  config/owasp/suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-message-publisher-pr-299
